### ISSUE TITLE
Regeln anlegen funktioniert nicht

### ISSUE THREAD

**Issue by moonglum** [hacken-in/website#360]
Man kann aktuell keine Regeln anlegen. Wenn man eine Zeit angibt (zB. 120) dann wird diese als Fehler markiert: "Muss größer als 0 sein" und das Feld ist gefüllt mit: -345669

**Comment by bitboxer** [comment]
Das ist gestern übrigens wieder passiert :( . Aber ich hab keinen plan woran das liegen könnte. Sehr mergkwürdiges verhalten.

**Comment by bitboxer** [comment]
Der @bascht hat im #566 das animierte gif hier gemacht: 

![bascht animiertes gif](https://cloud.githubusercontent.com/assets/51264/6263258/b2e146a4-b814-11e4-8ead-51b06ebbe78f.gif)

**Comment by bascht** [comment]
Die Neugier war groß und ich habe doch noch mal reingeschaut. Und siehe da: Rails hat ja eigene Vorstellungen der Zeitzone (`config.time_zone`) - die schedule im Event wurde aber ohne Zeitzone hinterlegt.

Wenn ihr oben im Dscccchiiiiifff genau hinschaut, seht ihr dass nicht nur die Länge immer kleiner wird, sondern auch die Uhrzeit immer schön um zwei Stunden pro Speichervorgang driftet.

Da wir ja schon einen spaßigen Stunt mit `fix_start_time` aus #308 haben, war ich mal so frei und habe an die `start_time` und `start_time=` Methoden ein `.in_time_zone('Europe/Berlin')` angehangen und siehe da: Die Zeit schwimmt nicht mehr davon! :dancers: 

Dann fing aber die Rails Rückrunde an: Das Setzen der `duration` (was wir ja eigentlich nur an `IceCube::Schedule` weiter reichen) klappt nicht (mehr?):

Sobald ich das Startdatum verändere, kommt die Differenz in der `duration` wieder. Dieses Mal aber reproduzierbar:

1. **Start:** 2011-08-11 mit **Duration**: 30
2. geändert auf **Start:** 2015-08-11
3. Speichern
4. :bomb:
5. Duration-Feld auf -126230400

Weil:

```ruby
Time.parse('2011-08-11 04:30:00 +0200') - Time.parse('2015-08-11 04:30:00 +0200')
=> -126230400.0
```
Eventuell einfach mal die Duration so wie in den IceCube Dokus nicht absolut sondern nach der Art `end_time = start_time + duration` setzen?

Mit diesen Worten zurück ins Studio. Habe mich nicht getraut `fix_start_time` anzufassen. Ich muss jetzt schlafen und alles was ich über `ActiveSupport::TimeZone` gelernt habe wieder vergessen.

Übrigens – `config.active_record.default_timezone` ist auch noch ein Schalter.

:zzz:

**Comment by moonglum** [comment]
Danke für die Untersuchung, Bascht. Das ist alles unglaublich :frowning: 

Liege aktuell flach und mein Gehirn ist aktuell definitiv nicht in der Lage für so was, sorry :cry:

**Comment by bitboxer** [comment]
@moonglum hast du irgrendwann mal zeit zum pairen hierzu?

**Comment by bitboxer** [comment]
Ich werde daran heute mal arbeiten.

**Comment by bascht** [comment]
…it took us one year to fix this bug – and we  even forgot about its birthday…!

![One year](http://www.howsweetbakery.com/Album/images/firstfirstcake.jpg)

Nevertheless: Thanks everyone! :+1: :cupid:

**Comment by moonglum** [comment]
That's amazing!!!!

**Comment by moonglum** [comment]
:tada:
