### ISSUE TITLE
Hamburger menu with scrollbars on mobile view

### ISSUE THREAD

**Issue by schultyy** [hacken-in/website#448]
When opening the Hamburger menu on mobile view, the browser shows scrollbars when the region does not have any events.
![screen shot 2014-12-28 at 22 34 05](https://cloud.githubusercontent.com/assets/235808/5565043/e68b820a-8ee1-11e4-8901-503a12d1dc0d.png)
The problem here is that the site does not have full height.

**Comment by bitboxer** [comment]
Should we just give it a min height? I have no clue how to fix it otherwise.

**Comment by moonglum** [comment]
Yep, I think a min-height will do.

**Comment by bitboxer** [comment]
Thanks to @gill0r this is fixed now.
