### ISSUE TITLE
Try out PhraseApp

### ISSUE THREAD

**Issue by moonglum** [hacken-in/website#450]
We were not really satisfied with LocaleApp. So I asked around for alternatives. @skade and @schultyy suggested [PhraseApp](https://phraseapp.com/en). Shall we try that?

**Comment by moonglum** [comment]
@bitboxer Doesn't i18n-tasks solve those problems for us? Maybe we should just use them and close this ticket?

**Comment by bitboxer** [comment]
Yes, a bit of it. We could try that.

**Comment by moonglum** [comment]
Ok, let's try it out. If we feel pain, we will open an issue :smile_cat: Closing now.
