### ISSUE TITLE
Reset Password: error 'Reset password token ist nicht gültig'

### ISSUE THREAD

**Issue by muescha** [hacken-in/website#489]
### reproduce

- requested password reset
- click on link in email
- type in new passwords

### problems

i get error message:

```
Konnte benutzer nicht speichern: ein Fehler.
- Reset password token ist nicht gültig
```

(note: the error message should be a red flash box to distinct from headline `Change your password` )

**Comment by bascht** [comment]
@muescha Thanks for reporting this. Fix is in #545.

Please file a separate issue for your »red flash box« suggestion, as this is part of our broader war on stylesheets. :)
