### ISSUE TITLE
ActiveRecord::StatementInvalid in statistics#show

### ISSUE THREAD

**Issue by bitboxer** [hacken-in/website#515]
## Exception in Hacken.in

**ActiveRecord::StatementInvalid** in **statistics#show**
PG::UndefinedFunction: ERROR:  function weekday(timestamp without time zone) does not exist
LINE 1: SELECT COUNT(*) AS count_all, weekday(occurrence) AS weekday...
                                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
: SELECT COUNT(*) AS count_all, weekday(occurrence) AS weekday_occurrence FROM &quot;single_events&quot; INNER JOIN &quot;events&quot; ON &quot;events&quot;.&quot;id&quot; = &quot;single_events&quot;.&quot;event_id&quot; WHERE ((single_events.region_id is not null and (single_events.region_id = 2 or single_events.region_id = 1)) or (single_events.region_id is null and (events.region_id = 2 or events.region_id = 1))) AND (occurrence &lt;= &#x27;2014-12-29&#x27;) GROUP BY weekday(occurrence)  ORDER BY &quot;single_events&quot;.&quot;occurrence&quot; ASC, single_events.name ASC, events.name ASC

[View on Bugsnag](https://bugsnag.com/hacken-dot-in/hacken-dot-in/errors/54a2e94f0d2531335064cfad?event_id=54a2ed5e322059f9234be99f)

## Stacktrace

    app/controllers/statistics_controller.rb:8 - show

[View full stacktrace](https://bugsnag.com/hacken-dot-in/hacken-dot-in/errors/54a2e94f0d2531335064cfad?event_id=54a2ed5e322059f9234be99f)

**Comment by bitboxer** [comment]
Jep :wink:

**Comment by moonglum** [comment]
Ah, SQL, you pretty little standard.
