### ISSUE TITLE
Deletion of Uberspace Account

### ISSUE THREAD

**Issue by bitboxer** [hacken-in/website#517]
I want to delete the uberspace account. We no longer use it. @moonglum and @bascht are you okay with that?

Archive…

- [x] The last active working directory (incl. whole Capistrano structure)
- [x] The last active MySQL database (+user tables)
- [x] The NGINX configuration
- [x] Old NGINX logs

**Comment by moonglum** [comment]
Yep :+1:

**Comment by bitboxer** [comment]
btw: someone is still automatically sending money to the uberspace account. Please stop that :)

**Comment by moonglum** [comment]
That would be me :blush: Will stop it this evening!

**Comment by bitboxer** [comment]
The uberspace is now closed, backuped and marked for deletion :cry:

**Comment by moonglum** [comment]
Thanks, @bitboxer !
