### ISSUE TITLE
update readme with new setup process

### ISSUE THREAD

**Issue by bitboxer** [hacken-in/website#519]
Thanks to @bascht we now have a nice setup script. Hooray.

The readme has to be updated for this.

**Comment by bitboxer** [comment]
Ping @bascht :smile:

**Comment by bascht** [comment]
\*cough\* still on it. Lost in post-congress-todos. :)

**Comment by bascht** [comment]
@moonglum @bitboxer @cashewkernchen give it a re-read if you have time. :)
