### ISSUE TITLE
make rake db:seed idempotent

### ISSUE THREAD

**Issue by bitboxer** [hacken-in/website#520]
The db seed needs to be changed so that it can run multiple times. This is needed for [this](https://github.com/hacken-in/puppet-hackenin/issues/4) ticket.

**Comment by moonglum** [comment]
Ok, so I looked into how to solve this. My solution would be to `find_or_create_by` the ID of each of the seed entries and then update their attributes.

So currently, the seeds look like this:

```ruby
Region.create([
  {id: 1, name: "Global",  slug: "global",   latitude: nil,     longitude: nil,     perimeter: nil,  active: true},
  {id: 2, name: "Köln",    slug: "koeln",    latitude: 50.946,  longitude: 6.95889, perimeter: 20.0, active: true},
  {id: 3, name: "Berlin",  slug: "berlin",   latitude: 52.5186, longitude: 13.4081, perimeter: 20.0, active: true},
  {id: 4, name: "München", slug: "muenchen", latitude: 48.1368, longitude: 11.5781, perimeter: 20.0, active: true},
  {id: 5, name: "Hamburg", slug: "hamburg",  latitude: 53.5653, longitude: 10.0014, perimeter: 20.0, active: false}
])
```

with the idea described above it would look like this:

```ruby
Region.find_or_create_by!(id: 1).update(name: "Global",  slug: "global",   latitude: nil,     longitude: nil,     perimeter: nil,  active: true)
Region.find_or_create_by!(id: 2).update(name: "Köln",    slug: "koeln",    latitude: 50.946,  longitude: 6.95889, perimeter: 20.0, active: true)
Region.find_or_create_by!(id: 3).update(name: "Berlin",  slug: "berlin",   latitude: 52.5186, longitude: 13.4081, perimeter: 20.0, active: true)
Region.find_or_create_by!(id: 4).update(name: "München", slug: "muenchen", latitude: 48.1368, longitude: 11.5781, perimeter: 20.0, active: true)
Region.find_or_create_by!(id: 5).update(name: "Hamburg", slug: "hamburg",  latitude: 53.5653, longitude: 10.0014, perimeter: 20.0, active: false)
```

Do you think that this is a good way to solve it, @bitboxer and @bascht? :smile:

**Comment by bascht** [comment]
Pragmatic. Like it.

**Comment by bitboxer** [comment]
I would prefer not to use ids but the slug and other things, because those ids could lead to messy stuff, but it would also mean rewriting the complete seed thing. So the pragmatic thing is okay :wink:

**Comment by moonglum** [comment]
Thanks for your feedback! Then I will implement it like that :+1:

**Comment by moonglum** [comment]
Ok, will need to do it a little different, because validations will fail if I only provide an ID :disappointed: 

The following thing needs to be done:

```ruby
Region.new(id: 1) do |region|
  region.assign_attributes(name: "Global",  slug: "global",   latitude: nil,     longitude: nil,     perimeter: nil,  active: true)
end
```

This would of course be a little crazy to do for every single item, so I will extract a tiny helper method:

```ruby
def seed_data(model, data)
  model.new(id: data.fetch(:id)) do |m|
    m.assign_attributes(data)
  end
end

seed_data(Region, {id: 1, name: "Global",  slug: "global",   latitude: nil,     longitude: nil,     perimeter: nil,  active: true})
```

**Comment by bascht** [comment]
So, would https://github.com/metaskills/named_seeds be worth a try?
There is certainly room for more Gems in our Gemfile. :)

**Comment by moonglum** [comment]
Noooooooooo more gems :fearful:
