### ISSUE TITLE
ActionView::Template::Error in admin/radar_entries#index

### ISSUE THREAD

**Issue by bitboxer** [hacken-in/website#537]
## Exception in Hacken.in

**ActionView::Template::Error** in **admin/radar_entries#index**
PG::UndefinedColumn: ERROR:  column radar_entries.event_id does not exist
LINE 1: ...CT  1 AS count_column FROM &quot;radar_entries&quot;  WHERE &quot;radar_ent...
                                                             ^
: SELECT COUNT(count_column) FROM (SELECT  1 AS count_column FROM &quot;radar_entries&quot;  WHERE &quot;radar_entries&quot;.&quot;event_id&quot; IN (568, 336, 539) AND &quot;radar_entries&quot;.&quot;state&quot; = &#x27;UNCONFIRMED&#x27; LIMIT 30 OFFSET 0) subquery_for_count

[View on Bugsnag](https://bugsnag.com/hacken-dot-in/hacken-dot-in/errors/54b2d01dc3bb24b164771d6c?event_id=54b2d06e1141f71e29013ad8)

## Stacktrace

    gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:822 - async_exec
    gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:822 - block in exec_no_cache
    gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract_adapter.rb:373 - block in log

[View full stacktrace](https://bugsnag.com/hacken-dot-in/hacken-dot-in/errors/54b2d01dc3bb24b164771d6c?event_id=54b2d06e1141f71e29013ad8)

**Comment by bitboxer** [comment]
If you are a curator, you can't see the radar entries. It crashes with this exception.

I think @skade "discovered" this one.

**Comment by skade** [comment]
Phew, I was just going through the issue list to see if that is already reported...
