### ISSUE TITLE
Twitter::Error in twitter:update_lists

### ISSUE THREAD

**Issue by bitboxer** [hacken-in/website#542]
## Exception in Hacken.in

**Twitter::Error** in **twitter:update_lists**
execution expired

[View on Bugsnag](https://bugsnag.com/hacken-dot-in/hacken-dot-in/errors/54b9e3380eb4aaa7d97168db?event_id=54b9e338f22db30e3c0155ad)

## Stacktrace

    lib/twitter_list_updater.rb:18 - block in add_missing_to_list
    lib/twitter_list_updater.rb:17 - each
    lib/twitter_list_updater.rb:17 - add_missing_to_list
    lib/twitter_list_updater.rb:11 - block in update
    lib/twitter_list_updater.rb:10 - update
    lib/tasks/twitter.rake:10 - block (2 levels) in &lt;top (required)&gt;

[View full stacktrace](https://bugsnag.com/hacken-dot-in/hacken-dot-in/errors/54b9e3380eb4aaa7d97168db?event_id=54b9e338f22db30e3c0155ad)

**Comment by bascht** [comment]
Version 5.6.0 of the twitter gem supports retry on timeouts: sferik/twitter@3179537a  – (and deprecates all the errors with the next versions, but that's another story). I'll bump the version and see if we can handle those errors.

**Comment by bitboxer** [comment]
## Resolved error re-occurred in Hacken.in

**Twitter::Error::RequestTimeout** in **twitter:update_lists**
execution expired

[View on Bugsnag](https://bugsnag.com/hacken-dot-in/hacken-dot-in/errors/54b9e3380eb4aaa7d97168db?event_id=54bdd7d965e09eb63e013b07)

## Stacktrace

    lib/twitter_list_updater.rb:18 - block in add_missing_to_list
    lib/twitter_list_updater.rb:17 - each
    lib/twitter_list_updater.rb:17 - add_missing_to_list
    lib/twitter_list_updater.rb:11 - block in update
    lib/twitter_list_updater.rb:10 - update
    lib/tasks/twitter.rake:10 - block (2 levels) in &lt;top (required)&gt;

[View full stacktrace](https://bugsnag.com/hacken-dot-in/hacken-dot-in/errors/54b9e3380eb4aaa7d97168db?event_id=54bdd7d965e09eb63e013b07)

**Comment by bascht** [comment]
Alright – I just wrapped the other two methods in the exception handler. If the problem reoccurs we have to increase the timeout and the number of retries.
