### ISSUE TITLE
Complete Favicon set

### ISSUE THREAD

**Issue by thegcat** [hacken-in/website#553]
http://realfavicongenerator.net/ should be able to generate us a full set of {web,ios,android,win tiles} icons.

**Comment by bascht** [comment]
Fun fact: I used Realfavicongeneratordotnet to generate the current set of icons in 8fb33a0810209ede47db315e4fe618cb8e613b85.
Are you missing any icon in particular?

**Comment by thegcat** [comment]
> (I skipped the Windows Icons + some of the Apple specific magic sizes)

I thought that was because it was "work" to create them, but if they're readily available and only need no or next to no maintenance, I don't see a reason to add the rest?

**Comment by muescha** [comment]
the favicon checker shows some more warnings:
http://realfavicongenerator.net/favicon_checker?site=hacken.in

**Comment by bascht** [comment]
Yep. I chose not to honk 8 more lines into our header. Especially the »tiles« stuff is ridiculous. As I said: @thegcat / @muescha if you are missing a particular icon set for your devices, I'd be more than happy to add it.

Otherwise I'd just close this issue. :smile_cat:

**Comment by bitboxer** [comment]
Yes, close it. Tons of icons just for the sake of it is not helping us in any way :)

**Comment by bascht** [comment]
decision-making. <3

**Comment by moonglum** [comment]
:+1:
