### ISSUE TITLE
Event Erstellung: Dauer in Minuten

### ISSUE THREAD

**Issue by madeleine-neumann** [hacken-in/website#566]
Ich habe alle benötigten Felder ausgefüllt und bei "Dauer in Minuten" die 60 Minuten drin gelassen, die standardmäßig eingetragen sind. Beim Submit motzt das Feld, dass meine Zahl größer als 0 sein muss und ändern die 60 auf einmal in: -28509

(Ich hatte das Event schon einmal angelegt, aber beim Filtern nach "Ruhrgebiet" taucht es nicht auf, Fehler ggf. aufgrund doppelten Eintrags?

Fehler siehe Screenshot: http://fs1.directupload.net/images/150218/nogl3g9k.png

**Comment by bascht** [comment]
Danke für den Report! Ist reproduzierbar – für Events, aber nicht für SingleEvents – in den Events finde ich aber nicht mal eine Duration im Model. Ich befürchte aber dass wir hier auf einen Rails-Notarzt warten müssen. @moonglum / @bitboxer to the rescue! :ambulance:

**Comment by bascht** [comment]
![out](https://cloud.githubusercontent.com/assets/51264/6263258/b2e146a4-b814-11e4-8ead-51b06ebbe78f.gif)
Mathematik!

**Comment by bitboxer** [comment]
Das ist leider schon bekannt als #360 . Der Lukas und ich wollten das eigentlich letzte Woche zusammen in einer pairing session reparieren, aber ich hab leider bei Bitcrowd noch 'nen Bastelsamstag gehabt :cry: . Wird zeit das wir das fixen. Ich verstehe halt nur nicht, wo das her kommt und brauch hilfe.

**Comment by moonglum** [comment]
Lucas, nicht Lukas :frowning:

**Comment by bitboxer** [comment]
Ich habe hier zu viele Luckase im Bekanntenkreis. Ab jetzt nene ich euch nur noch Luckas. Dann hat jeder was zu beschweren :wink:

**Comment by muescha** [comment]
wie wärs mit einem regex konformen `Lu(c|k)as` oder `Lu[ck]as`

**Comment by moonglum** [comment]
:tongue:
