### ISSUE TITLE
Code coverage is "unknown"

### ISSUE THREAD

**Issue by bascht** [hacken-in/website#586]
![screenshot from 2015-04-23 20 42 35](https://cloud.githubusercontent.com/assets/51264/7304691/55fae03c-e9f9-11e4-88af-ad05872aa03f.png)
Looks like we broke / misconfigured something.

**Comment by bascht** [comment]
Let's wait until #604 is in master.

**Comment by railsbros-dirk** [comment]
I think this issue can be closed. Code Coverage badge is up and running again.

**Comment by bascht** [comment]
@railsbros-dirk Thanks for the heads up! You're right: https://codeclimate.com/github/hacken-in/website looks fine! :)

**Comment by moonglum** [comment]
👌
