### ISSUE TITLE
ActionView::Template::Error in single_events#show

### ISSUE THREAD

**Issue by bitboxer** [hacken-in/website#594]
## Exception in Hacken.in

**ActionView::Template::Error** in **single_events#show**
undefined method &#x60;color&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/hacken-dot-in/hacken-dot-in/errors/5546a52ad4b5f4b0e49f17b6?event_id=5546a52a5d186b5a23f3ecf3)

## Stacktrace

    app/views/modules/categories/_indicator.html.haml:1 - _app_views_modules_categories__indicator_html_haml__2871570490134160349_86693600
    app/views/single_events/show.html.haml:15 - _app_views_single_events_show_html_haml___862817483225247207_87524460
    app/controllers/single_events_controller.rb:11 - show

[View full stacktrace](https://bugsnag.com/hacken-dot-in/hacken-dot-in/errors/5546a52ad4b5f4b0e49f17b6?event_id=5546a52a5d186b5a23f3ecf3)

**Comment by bascht** [comment]
Looks like we expect every Category to have a colour while this isn't always the case:

```haml
.indicator{style: "background-color: #{category.color};", title: category.title}
```

**Comment by moonglum** [comment]
I think that I coded that a while ago. The question is: Why is this assumption not valid? We should probably enforce this. What do you think?

**Comment by bascht** [comment]
@moonglum Yep – I already thought about adding a colour / color wrapper to the `Category` model, but I don't know the nuts and bolts of Category / SingleEvents. :)
