### ISSUE TITLE
Ruhrgebiet auf die Map

### ISSUE THREAD

**Issue by moonglum** [hacken-in/website#597]
Das Ruhrgebiet ist bereit freigeschaltet zu werden. Es muss nur noch auf die Karte gesetzt werden :smile: Sobald das passiert ist, @madeleine-neumann Bescheid sagen. Das Ruhrgebiet ist [hier](https://hacken.in/ruhrgebiet) zu finden.

**Comment by bascht** [comment]
Das Ruhrgebiet sehe ich auch schon auf hacken.in live. Close?

**Comment by moonglum** [comment]
Yep!
