### ISSUE TITLE
Spam Issue :(

### ISSUE THREAD

**Issue by moonglum** [hacken-in/website#649]
We had a big spam attack last weekend. I think the best solution would be to deactivate comments. They are rarely used and not worth the struggle.

**Comment by muescha** [comment]
Alternativ könnte man externe Kommentarfunktion nutzen:

Möglichkeiten:
- disqus
- facebook

Die Kommentar Funktion war meist für den Fall nützlich, wenn man Änderungen kommunizieren möchte die zwar auf der Homepage des Events zu sehen waren, aber noch nicht auf hacken geändert wurde. Meistens fällt einem sowas am selben Tag auf.

**Comment by moonglum** [comment]
Removed the comments feature.
